### ISSUE TITLE
ページ 24, リスト 3.4 のクエリでエラーになる

### ISSUE THREAD

**Issue by giantneco** [kazuyaseki/matering-apollo-client#3]
ページ 24, リスト 3.4 にあるようにクエリを変更すると React App 側で `GraphQLError: Syntax Error: Expected Name, found {` とエラーがでて、次のように syntax error が指摘される。

```
   6 | import SearchField from './components/SearchField';
   7 | import RepoItem from './components/RepoItem';
   8 | 
>  9 | const query = gql`
  10 |   query search($searchText: String!) {
  11   |   {
  12 |       search(query: $searchText, type: REPOSITORY, first: 10) {
```

上記の 11 行目の`{` とそのペアを除くとエラーが解消されたのでおそらく記述間違いと思われる。

**Comment by seya613** [comment]
ご報告ありがとうございます！こちら確かにご指摘の通りクエリ内の `{}` が多かったためエラーになってしまうようです。

ご迷惑をおかけし申し訳ございません。正誤表に記載させていただきます。
