### ISSUE TITLE
ページ 21 リスト 3.2 に関する記述漏れ

### ISSUE THREAD

**Issue by giantneco** [kazuyaseki/matering-apollo-client#4]
ページ  21 リスト 3.2 の 5 行目にあるように一部コードを AppResources.js に移動したことが記述漏れになっている。

git の別ブランチを見てどうなっているか初めてわかったので、ちょっと不親切と思います。

**Comment by kazuyaseki** [comment]
確かに急に移動していますね…。配慮が足らず申し訳ございません。
`master` ブランチと `01-HelloWorld` ブランチの時点でちゃんとAppResources.jsがあるように修正いたします。

**Comment by kazuyaseki** [comment]
こちら修正いたしました！ ご指摘ありがとうございましたm(__)m
